use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NpuArchitecture {
    AppleNeuralEngine, // Apple Silicon ANE (M1/M2/M3/M4/etc.)
    IntelNPU,          // Intel VPU/NPU (Meteor Lake, Lunar Lake, Arrow Lake)
    AmdRyzenAI,        // AMD XDNA / XDNA 2
    QualcommHexagon,   // Snapdragon NPU
    GenericComputeFallback, // AVX-512 / AMX / Metal Compute
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NpuBackend {
    CoreML,
    MetalPerformanceShaders,
    OpenVINO,
    DirectML,
    OnnxRuntime,
    AccelerateCpu,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NpuDeviceInfo {
    pub name: String,
    pub architecture: NpuArchitecture,
    pub backend: NpuBackend,
    pub estimated_tops: f32,
    pub is_available: bool,
    pub driver_info: String,
    pub supported_precisions: Vec<String>,
    pub zero_copy_unified_memory: bool,
}

/// Dynamic rate control & quantization decisions generated by the NPU
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiEncodingPlan {
    pub recommended_crf: u8,
    pub max_bitrate_kbps: Option<u32>,
    pub qp_offset: i8,
    pub enable_perceptual_aq: bool,
    pub motion_complexity_score: f32, // 0.0 (static) to 1.0 (very high motion)
    pub spatial_complexity_score: f32,// 0.0 (smooth) to 1.0 (fine textures/noise)
    pub estimated_bitrate_reduction_percent: f32, // e.g. 35.0%
    pub scene_change_detected: bool,
}

/// Saliency assessment of a frame or GOP
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SaliencyAssessment {
    pub timestamp_sec: f64,
    pub frame_index: usize,
    pub foveated_center_x: f32,
    pub foveated_center_y: f32,
    pub complexity: f32,
    pub is_scene_cut: bool,
    pub suggested_gop_type: GopFrameType,
}

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GopFrameType {
    KeyframeIDR,
    PFrameFastSkip,
    BFramePerceptual,
}
